name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Code aus dem Repository auschecken
    - uses: actions/checkout@v4

    # Login in die GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Docker-Image bauen
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/kohlhaas1808/comfyui:latest

    # Docker-Image pushen
    - name: Push the Docker image
      run: docker push ghcr.io/kohlhaas1808/comfyui:latest
